sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install
script: npm run lint && npm run build && npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: bGmMCvdwcjAATZNwPHJR0arbkfQ5Ic50kpbdDWPoxrw3kuhuQk4hm6pHDOhRNeRedoRgvdaLj0kCQ7t0QjiwZxLTYZGYSaIFk9+GPCl0ZEgMJduR2DthovkfoSSzj2bBMZAIhazT32HUYUr72BnVQ2fE3wbAF8cUCuuJLn8MrBq3PnwUkbydLPCjtbx73zqCndefPVMAet5lJ3lJgOevroRahvBCTc5uR+hfR4WHWlVbdkMLwZyfXe9kuXZ/oxQrzzArRSTzy1/4b1rhHa+nES/BTE9fQfluaCJssxLUjMFBBn9p5QKybwrk+CT8cGW8Zcgd+ZVJcokhzewSdUsIsMfqljgLc0Bw/sg0/Q0aiXYm2r03evO/mFTyKiFMWdyZmTazTcfctJY5BONBLbOTDsQbsdJFxUG0oK3v/k0CY6MBVEEPOk6urjldy1EKAiMk+4MqjwaPwDVNu4cF8ytdI5vqgTly9xxbmm+yaluUqQJG1Ne7k+rgoEKUV2+IdAO1pLdCcczVp+qta0xUCzOC0u4rpTMoo9K7ZmNl1Z+MZWcs3/AU0wk6ldc2TKl1swB0IP2eC/4JY+e8eYSt3mBDbJ5icOTJqZj30tr9t5o8ZWJhtJrpw7EmQM/fjc/uwSyYF1p1fbkFfKDCM7CEl4PfbLhnXlV0YUgoYxg+VmcEJF4=
  on:
    tags: true
    node_js: "7"
